version: '3.8'

services:
  api:
    build: ./api
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./shared-data:/data
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/db-data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./Proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./Proxy/mime.types:/etc/nginx/mime.types
      - ./shared-data:/data

volumes:
  shared-data:
  db-data: